### ISSUE TITLE
logging in as an admin doesn't show the qr-code any longer

### ISSUE THREAD

**Issue by ghost** [hzi-braunschweig/pia-system#11]
![image](https://user-images.githubusercontent.com/69628891/196980921-f7b4684c-50bf-4616-8e30-72edb51a832e.png)

Before version 1.30.1, I could see the QR code here to create the one-time-code. Currently, as seen in the screenshot, no QR code is shown (versions 1.30.1 and 1.30.2).

**Comment by RobYed** [comment]
@joerghenkebuero 
This is the expected behaviour of the newly introduced 2-factor-authentication (2FA). 

In the first step you already connected your Google Authenticator or whatever secound factor you are using. This was the initial setup. From now on you only need to enter a one-time token, which your Authenticator is generating every 30 secounds.

In case you loose your secound factor, you may use the password reset feature to reset not only your password but also your secound factor.

Hope that helps.
Robert

**Comment by ghost** [comment]
thank you, this has solved the problem. Besides, I'd like to deactivate the 2f authorization for the admin role - a pity that this is not possible.

**Comment by RobYed** [comment]
PIA is meant to be a public facing app. The admin role allows potential attackers to read, manipulate or even delete your highly sensitive data. We think that it is a good idea to add another security layer to further secure this special role.

Glad, I could help.
